import React from 'react';
import PropTypes from 'prop-types';
import StreamObj from '../utils/streamObj';
import unzip from '../utils/unzip';
import handleText from '../utils/handleText';
import fileReader from '../utils/fileReader';
import { Setting, Buttons, Explain, FileInput } from '../style/Styles';

class ImportPdf extends React.Component {
  constructor(props) {
    super(props);
    if (localStorage.data) {
      this.state = JSON.parse(localStorage.data);
    } else {
      this.state = {
        songInput: '',
        prevInput: '',
      };
    }
    this.handleFileSelect = this.handleFileSelect.bind(this);
  }

  handleFileSelect(e) {
    const { files } = e.target;
    const { goBack } = this.props;
    fileReader(files[0])
      .then(songBuff => new StreamObj(songBuff))
      .then(stream => unzip(stream.primero))
      .then(unzipped => unzipped.split('ET').map(idx => idx.split('BT')[1]))
      .then(charArr =>
        this.setState({
          songInput: handleText(charArr),
        })
      )
      .then(() => localStorage.setItem('data', JSON.stringify(this.state)))
      .then(() => goBack());
  }

  render() {
    const { goBack } = this.props;
    return (
      <Setting>
        <Explain>
          *** This Import PDF tool currently only works with single-page song
          PDFs generated by Planning Center Online
        </Explain>
        <FileInput
          type="file"
          name="importPdf"
          onChange={this.handleFileSelect}
        />
        <Buttons onClick={goBack}>Go Back</Buttons>
      </Setting>
    );
  }
}

ImportPdf.propTypes = {
  goBack: PropTypes.func.isRequired,
};

export default ImportPdf;
